apiVersion: v1
kind: Service
metadata:
  name: airports-service
  labels:
    app: airports-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
      protocol: TCP
  selector:
    app: airports
