apiVersion: v1
kind: Secret
metadata:
  name: airports-secret
type: Opaque
stringData:
  rabbit_user: guest
  rabbit_password: guest
  rabbit_host: mq
  rabbit_port: 5672
  redis_host: redis-airports-service
  redis_port: 6379