apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  rabbit_user: guest
  rabbit_password: guest
  rabbit_host: rabbitmq-service
  rabbit_port: "5672"
  airports_health_check: http://airports-service:8000/health
  trips_health_check: http://trips-service:8000/health