apiVersion: v1
kind: Service
metadata:
  name: trips-service
  labels:
    app: trips-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    app: trips
