apiVersion: v1
kind: Secret
metadata:
  name: trips-secret
type: Opaque
stringData:
  rabbit_user: guest
  rabbit_password: guest
  rabbit_host: mq
  redis_host: redis-trips-service
  redis_port: 6379


