apiVersion: v1
kind: Secret
metadata:
  name: airports-secret
type: Opaque
stringData:
  rabbit_user: {{ .Values.airports_rabbit_user }}
  rabbit_password: {{ .Values.airports_rabbit_password }}
  rabbit_host: {{ .Values.airports_rabbit_host }}
  rabbit_port: {{ .Values.airports_rabbit_port }}
  redis_host: {{ .Values.airports_redis_host }}
  redis_port: {{ .Values.airports_redis_port }}