apiVersion: v1
kind: Service
metadata:
  name: redis-trips-service
  labels:
    app: redis-trips-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-trips
