apiVersion: v1
kind: Service
metadata:
  name: redis-trips-service
  labels:
    app: redis-trips-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    app: redis-trips
