apiVersion: v1
kind: Secret
metadata:
  name: trips-secret
type: Opaque
stringData:
  rabbit_user: {{ .Values.trips_rabbit_user }}
  rabbit_password: {{ .Values.trips_rabbit_password }}
  rabbit_host: {{ .Values.trips_rabbit_host }}
  rabbit_port: {{ .Values.trips_rabbit_port }}
  redis_host: {{ .Values.trips_redis_host }}
  redis_port: {{ .Values.trips_redis_port }}
