apiVersion: v1
kind: Secret
metadata:
  name: trips-secret
type: Opaque
stringData:
  rabbit_user: guest
  rabbit_password: guest
  rabbit_host: rabbitmq-service
  rabbit_port: "5672"
  redis_host: redis-trips-service
  redis_port: "6379"
