apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  rabbit_user: {{ .Values.gateway_rabbit_user }}
  rabbit_password: {{ .Values.gateway_rabbit_password }}
  rabbit_host: {{ .Values.gateway_rabbit_host }}
  rabbit_port: {{ .Values.gateway_rabbit_port }}
  airports_health_check: {{ .Values.gateway_airports_health_check }}
  trips_health_check: {{ .Values.gateway_trips_health_check }}